---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Set affected device from event
      ansible.builtin.set_fact:
        source: "{{ ansible_eda.event.tags.source }}"
        timestamp: "{{ ansible_eda.event.timestamp }}"

    - name: Inform NetOps team about the incident
      community.general.cisco_webex:
        recipient_type: roomId
        recipient_id: "{{ WEBEX_RECIPIENT_ID }}"
        msg_type: text
        personal_token: "{{ WEBEX_PERSONAL_TOKEN }}"
        msg: "High CPU utilization detected on {{ source }} at {{ '%Y-%m-%d %H:%M:%S %Z'|strftime(timestamp) }}"
